header:
  version: 10
distro: phire
local_conf_header:
  bmap: IMAGE_FSTYPES += "wic.gz wic.bmap"
repos:
  meta-phire:
    layers:
      meta-phire:
  bitbake:
    url: git://github.com/openembedded/bitbake
    refspec: 1428128c787642dca690a7d51f2be793e001ae37
    path: bitbake
    layers:
      .: excluded
  openembedded-core:
    url: git://github.com/openembedded/openembedded-core
    refspec: eeae63c343c8ebd418679915ee20aa8c02fa0fdc
    path: oe-core
    layers:
      meta:
  meta-openembedded:
    url: git://github.com/openembedded/meta-openembedded
    refspec: 0fb490a08ce30b47a5ccd2fdc3448b08e0d9e4e9
    path: meta-oe
    layers:
      meta-oe:
      meta-filesystems:
      meta-multimedia:
      meta-networking:
      meta-python:
        #    patches:
        #      mpd:
        #        repo: meta-phire
        #        path: kas/patches/fix-mpd-packageconfig.patch
  meta-rust:
    url: git://github.com/meta-rust/meta-rust
    refspec: c654f5cb928bd4f4c7da7d74a8356fd2a94283f6
    path: meta-rust
  meta-linux-mainline:
    url: https://git.sr.ht/~pbarker/meta-linux-mainline
    refspec: 8150e0ec4d7a0712b5f2ead7bbb639b832490b15
